version: '3.8'
services:
  node:
    restart: always
    build: 
        context: .   
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/app/
      - /app/node_modules
  mongo:
    restart: always
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
